version: '1.0'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_DATABASE: db_mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: localhost
    volumes:
      - ./dataMySQL:/var/lib/mysql
    restart: unless-stopped