version: '1.0'

services:
   postgres:
    image: postgres:latest
    network_mode: bridge
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: ThePassword
      POSTGRES_DB: db_postgres
    volumes:
      - ./dataPostgreSQL:/var/lib/dataPostgreSQL
    restart: unless-stopped